#!/usr/bin/python

import os
import sys
import select
import traceback
sys.path.insert(0,"/home/yurix/eucalyptus/common")
from c2.hw.chassis.ipmi.scanner import IPMIv2_SCANNER
from c2.hw.chassis.config import get_ifaces,all_local_networks,specific_networks

print get_ifaces()

print all_local_networks()

print specific_networks(set(['management']))
