#!/usr/bin/python
import sys
sys.path.insert(0,"/home/yurix/eucalyptus/common")
import c2.hw.chassis.identify as identify
from c2.hw.chassis.service_processor import ServiceProcessor

username = 'root'
password = 'calvin'
hostname = '172.25.6.221'

print "Testing mac_by_ip:"
mac = identify.mac_by_ip(hostname)
print mac

print "Testing mac preffix:"
print identify.macpreffix(mac)
print "Testing vendor_by_mac:"
print identify.vendor_by_mac(mac)
print "Testing macpreffix:"
print identify.macpreffix("00:01:FF:12:13:14")
print "Testing vendor_by_mac:"
print identify.vendor_by_mac("00:ZZ:FF:12:13:14")

print "Testing guess_sptype_by_http:"
print identify.guess_sptype_by_http(hostname)
print identify.guess_sptype_by_http("172.24.8.139")
print identify.guess_sptype_by_http("172.24.8.13")

print "Testing suggest_sptype:"
print identify.suggest_sptype("172.25.4.64")
print identify.suggest_sptype("172.24.8.107")
print identify.suggest_sptype("172.24.8.139")
print identify.suggest_sptype(hostname)

