#!/usr/bin/python
import os
import sys
import select
import traceback
sys.path.insert(0,"/home/yurix/eucalyptus/common")
from c2.hw.chassis.ibm.scanner import IBM_SCANNER

c=IBM_SCANNER()
targets=c.scan_blindly()

print str(targets)

for t in targets.keys():
    print "{0:39} {1}".format(t, targets[t]['proto'])

