#!/usr/bin/python

import os
import sys
import select
import traceback
sys.path..insert(0,"/home/yurix/eucalyptus/common")
from c2.hw.chassis.dell.idrac6 import DELLiDRAC6

username = 'root'
password = 'calvin'
hostname = '172.25.6.221'

# now connect
sp = DELLiDRAC6(hostname, username, password)

sp.connect()

print sp.powerstate()

if sp.alive():
    print 'ALIVE'
else:
    print 'NOT ALIVE'

#print sp.poweron()
print sp.getpxeboot()
#print sp.setpxeboot()
print str(sp.getvpd())

sp.disconnect()
