#!/usr/bin/python

import os
import sys
import select
import traceback
sys.path.insert(0,"/home/yurix/eucalyptus/common")
from c2.hw.chassis.wbem.generic import WBEM

username = 'USERID'
password = 'PASSW0RD'
hostname = '172.24.8.107'
hostname = '172.24.8.139'
hostname = '172.24.8.140'

# now connect
sp = WBEM(hostname, username, password)

print sp.connect()

#print sp.powerstate()

#if sp.alive():
#    print 'ALIVE'
#else:
#    print 'NOT ALIVE'

#print sp.poweron()
#print sp.getpxeboot('31B991EFE0BE38A8A2DB8141A673E4A3')
print sp.getpxeboot('25E7D6B4BD37312E94DDBADB386A1D0F')
#print sp.getbootlists('25E7D6B4BD37312E94DDBADB386A1D0F')
#print sp.setpxeboot()
#print str(sp.getvpd())

sp.disconnect()
