#!/usr/bin/python
import os
import sys
import select
import traceback
from ssp.scanner import Scanner

c=Scanner()
targets=c.scan()

print str(targets)

for t in targets.keys():
    print "{0:39} {1}".format(t, targets[t]['proto'])
